name: smartest_zone_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  clerk_flutter: ^0.0.8-beta
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  mobile_scanner: ^5.0.0
  uuid: ^4.2.1
  intl: ^0.20.2
  flutter_svg: ^2.0.9
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
